### ISSUE TITLE
fix login/signup links when user is signed in

### ISSUE THREAD

**Issue by DavidPomarede** [brityank/flexspace#17]

**Comment by kevdsteele** [comment]
This was fixed Sat by adjusting the login/signup html routes to the below.

app.get("/login", function(req, res, next) {
    // If the user already has an account send them to the members page
    if (req.user) {
      return res.redirect("/members");
      next()
    }
    var ejsObj = {pageTitle: "Login"};
    res.render("pages/login", ejsObj);
  });
